version: '3.8'

services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
